name: Feature Request
description: Suggest a new feature for Claude Cruise
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We'd love to hear your ideas.

  - type: textarea
    id: problem
    attributes:
      label: Problem you're trying to solve
      description: Describe the problem this feature would address
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe your ideal solution to this problem
      placeholder: "I'd like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What alternatives have you considered?
      placeholder: "I've also thought about..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples
      placeholder: Any additional information
